nome=input("Digite o Nome do Funcionario: ")
empresa=input("Digite o Nome da Empresa: ")
qntdd_funcionarios=int(input("Digite a Quantidade de funcionarios: "))
valor_mensalidade=float(input("Digite o Valor da Mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("a media da mensalidade é: " + str(valor_mensalidade))
print("A variavel (nome) é uma:", type(nome))
print("A variavel (empresa) é uma:", type(empresa))
print("A variavel (qntdd_funcionairios) é uma:", type(qntdd_funcionarios))
print("A variavel (valor_mensalidade) é uma:", type(valor_mensalidade))